keywords={
        ".5" : "FOR[ITERATION]",
        "wrap" : "KEYWORD\t",
        "as" : "KEYWORD[ASSIGNMENT]",
        "let" : "KEYWORD[RELOP]",
        "pp" : "INCRE[RELOP]",
        ".2" : "IF[CONDITIONAL]",
	"vomit" : "KEYWORD[PRINT]",
	"|" : "PARANTHESIS",
	"--" : "OPEN CONDITION",
	".3" : "ELSE-IF",
	"eq" : "EQ_OPERATOR",
	"neq": "NOT_EQ_OPERATOR",
	"let" : "REL_OPERATORS",
	"lete": "REL_OPERATORS",
	"get": "REL_OPERATORS",
	"gete": "REL_OPERATORS",
	"goto" : "JUMP_STATEMENTS",
	"continue" : "JUMP_STATEMENTS",
	"break" : "JUMP_STATEMENTS",
	"return" : "JUMP_STATEMENTS",
	"$$" : "OR OPERATOR",
	"&&" : "AND OPERATOR",
	"---" : "CLOSE CONDITION",
	".4" : "ELSE[SELECTION]",
	".6" : "WHILE\t",
	".7" : "DO[CONDITION]",
	":" : "SEPERATOR"
        }

